import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import fire from "../config/fire-config"
import { useEffect, useState } from 'react';

export default function Home() {
  
  const doc = fire.firestore().collection('listvideos');
  var request;
  

  const getBase64FromUrl = async (url) => {
  //  console.log(url)

    const data = await fetch(url,{method:"get", "access-control-allow-origin" : "*",});
    const blob = await data.blob();
    console.log(blob)
    return new Promise((resolve) => {
      const reader = new FileReader();
      reader.readAsDataURL(blob); 
      reader.onloadend = () => {
        const base64data = reader.result;   
      // setImgSel(prev=>[...prev,base64data])
          setUrl(prev=>[...prev,base64data])
           resolve(base64data);
           console.log(request)
           request.onupgradeneeded = function (event) {
                console.log("entroiu")
                console.log(event)
                var db = event.target.result;
          
                // Criando outro objeto chamado "names" com o autoIncrement setado.
                var objStore = db.createObjectStore("names", { autoIncrement : true });
          
                
                    objStore.add({img:base64data});
          
            }
      }
    });
  }

const [url,setUrl] = useState([]);

useEffect(()=>{
    if(typeof window !== undefined){
      console.log("entrou aqui")
      console.log("indexou")
      request = window.indexedDB.open("DBteste");

    }
},[])

useEffect(()=>{


 doc.onSnapshot(docSnapshot => {
    setUrl([]);
    docSnapshot.forEach((async x=>{
        console.log(x.id)
        const url = "http://btgnews.com.br/videos/"+x.id+"?to=crop&r=256";
        const src = await getBase64FromUrl(url);
       // console.log(url)
      //  console.log(src)
//setUrl(src);
    }))


  }, err => {
    console.log(`Encountered error: ${err}`);
  });



},[])

function Imagens(){
  return( url.map(u => {
      return(<img src={u}/>)
    })
    )
}

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Imagens/>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
     
        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
